version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
  client:
    container_name: react
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - server
